name: arXiv

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #schedule:
  #  - cron: '0 3 * * *' 

jobs:
  build:
    permissions:
      actions: write
      checks: write
      contents: write
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3 

      - name: Setup python 
        uses: actions/setup-python@v3 
        with:
          python-version: "3.10" 

      - name: Run arxiv.py 
        run: |
          python arxiv.py 
      
      - name: commit files
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "51148545+${{ github.actor }}@users.noreply.github.com" 
          git commit -am 'update README.md'
          git push origin main
